server:
  port: 9092
spring:
  application:
    name: payment-api
  cloud:
    openfeign:
      client:
        config:
          mercadopago:
            defaultRequestHeaders:
              authorization: Bearer ${application.mercadopago.accessToken}
            url: ${application.mercadopago.url}
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_api
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  rabbitmq:
    addresses: amqp://localhost:5672
    username: guest
    password: guest

application:
  queue:
    paymentStatusChanged:
      name: payment-status-changed
  mercadopago:
      url: https://api.mercadopago.com
      userId: fake
      posId: fake
      accessToken: fake
      callbackUrl: fake
